export enum NetworkName {
    Arbitrum = 'arbitrum',
    ArbitrumNova = 'arbitrum-nova',
    Base = 'base',
    LineaMainnet = 'linea-mainnet',
    Optimism = 'optimism',
    Avalanche = 'avalanche',
    Zora = 'zora',
    Scroll = 'scroll',
    Polygon = 'matic',
    PolygonzkEVM = 'polygon-zkevm',
    Mantle = 'mantle',
    ZkSync = 'zksync-era',
    BSC = 'bsc',
    Celo = 'celo',
    Core = 'coreDao',
    Gnosis = 'gnosis',
    Harmony = 'harmony',
}